# Makefile generated by genmake.pl
# Written by Ramo

CC=g++
BUILD=build
DIST=dist
CCFLAGS=-c -g -Wall --std=c++11
LDFLAGS=-o $(DIST)/prog -lpthread 

all:	$(DIST)/prog
$(DIST)/prog:	$(BUILD) $(DIST) $(BUILD)/results.o $(BUILD)/main.o $(BUILD)/notify.o 
	$(CC) $(BUILD)/*.o $(LDFLAGS)
$(BUILD)/results.o:	results.cpp results.h
	$(CC) results.cpp $(CCFLAGS) -o $(BUILD)/results.o
$(BUILD)/main.o:	main.cpp notify.h results.h
	$(CC) main.cpp $(CCFLAGS) -o $(BUILD)/main.o
$(BUILD)/notify.o:	notify.cpp notify.h results.h
	$(CC) notify.cpp $(CCFLAGS) -o $(BUILD)/notify.o
$(BUILD):
	@mkdir $(BUILD)
$(DIST):
	@mkdir $(DIST)
clean:
	rm -rf $(BUILD) $(DIST)
install:
	install $(DIST)/prog /usr/local/bin/
love:
	@echo Not war
